### PR TITLE
modularized cmd args and formatted code

### PR DESCRIPTION
**Pull request by Better-Boy**
code formatted according to pylint. Getting a rate of 9+ /10 for both the files. First level Modularization done. Tested the code on my local machine ,working fine

### CODE REVIEW

**Comment by sreekaransrinath** [comment]
Looks good to me @Better-Boy . Although, I just want to make sure, did you try running the script on your machine after you made these changes? 

Also, I'd like to DM you about something. Where would you prefer me to do it?

**Comment by Better-Boy** [comment]
I basically use macbook. Hence, I tested out this file and it works fine. Sure you can DM me.

**Comment by sreekaransrinath** [comment]
Can't DM you on GitHub, I'll shoot you an email.

**Comment by Better-Boy** [comment]
Sure

**Pull request merged**
